server:
  port: 9092
  
spring:
  datasource:
    url: jdbc:mariadb://192.168.56.101:3306/vive_valle_grande
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    
cl:
  silvercloud:
    tiendas:
      sql:
        add-empresa: insert into tb_empresa (nombre, rubro, pagina_web, tags, descripcion) values(?, ?, ?, ?, ?)
        select-empresa: select id, nombre, rubro, pagina_web, tags, descripcion from tb_empresa where id = ?